"""initial schema — users, login_history, medicines, stock_movements, sales, sale_items, activity_logs

Revision ID: 0001
Revises:
Create Date: 2026-08-20

Note: written by hand against the approved architecture doc rather than
autogenerated, since there was no live Postgres instance available to
autogenerate against. Table order respects foreign key dependencies:
users -> login_history -> medicines -> stock_movements -> sales -> sale_items
                                                          -> activity_logs

Hardening pass (still within 0001, since this had not yet been applied to
any live database): added CHECK constraints for
medicines.purchase_price >= 0, medicines.selling_price >= 0,
medicines.minimum_stock >= 0, medicines.critical_stock >= 0,
sale_items.quantity > 0, and stock_movements.change_qty <> 0.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("username", sa.String(50), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("fullname", sa.String(100), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("failed_logins", sa.Integer, nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("role IN ('Admin', 'Pharmacist')", name="ck_users_role"),
    )
    op.create_index("ix_users_username", "users", ["username"])

    op.create_table(
        "login_history",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("username_tried", sa.String(50), nullable=False),
        sa.Column("success", sa.Boolean, nullable=False),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "medicines",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("generic_name", sa.String(100), nullable=False),
        sa.Column("medicine_class", sa.String(100), nullable=True),
        sa.Column("brand_name", sa.String(100), nullable=False),
        sa.Column("dosage", sa.String(50), nullable=True),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("minimum_stock", sa.Integer, nullable=False, server_default="10"),
        sa.Column("purchase_price", sa.Numeric(10, 2), nullable=False),
        sa.Column("selling_price", sa.Numeric(10, 2), nullable=False),
        sa.Column("expiry_date", sa.Date, nullable=False),
        sa.Column("date_added", sa.Date, nullable=False, server_default=sa.func.current_date()),
        sa.Column("batch_number", sa.String(50), nullable=True),
        sa.Column("supplier", sa.String(100), nullable=True),
        sa.Column("date_received", sa.Date, nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="Active"),
        sa.Column("critical_stock", sa.Integer, nullable=False, server_default="3"),
        sa.CheckConstraint("status IN ('Active', 'Discontinued')", name="ck_medicines_status"),
        sa.CheckConstraint("quantity >= 0", name="ck_medicines_quantity_nonnegative"),
        sa.CheckConstraint("purchase_price >= 0", name="ck_medicines_purchase_price_nonnegative"),
        sa.CheckConstraint("selling_price >= 0", name="ck_medicines_selling_price_nonnegative"),
        sa.CheckConstraint("minimum_stock >= 0", name="ck_medicines_minimum_stock_nonnegative"),
        sa.CheckConstraint("critical_stock >= 0", name="ck_medicines_critical_stock_nonnegative"),
    )
    op.create_index("ix_medicines_generic_name", "medicines", ["generic_name"])
    op.create_index("ix_medicines_supplier", "medicines", ["supplier"])

    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("medicine_id", sa.Integer, sa.ForeignKey("medicines.id"), nullable=False),
        sa.Column("change_qty", sa.Integer, nullable=False),
        sa.Column("reason", sa.String(30), nullable=False),
        sa.Column("note", sa.Text, nullable=True),
        sa.Column("performed_by", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "reason IN ('received','sale','adjustment','damaged','expired','correction','other')",
            name="ck_stock_movements_reason",
        ),
        sa.CheckConstraint("change_qty <> 0", name="ck_stock_movements_change_qty_nonzero"),
    )

    op.create_table(
        "sales",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("receipt_number", sa.String(30), nullable=False, unique=True),
        sa.Column("sold_by", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("total_amount", sa.Numeric(10, 2), nullable=False),
        sa.Column("total_profit", sa.Numeric(10, 2), nullable=False),
        sa.Column("sale_date", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_sales_receipt_number", "sales", ["receipt_number"])

    op.create_table(
        "sale_items",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("sale_id", sa.Integer, sa.ForeignKey("sales.id"), nullable=False),
        sa.Column("medicine_id", sa.Integer, sa.ForeignKey("medicines.id"), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False),
        sa.Column("purchase_price", sa.Numeric(10, 2), nullable=False),
        sa.Column("selling_price", sa.Numeric(10, 2), nullable=False),
        sa.Column("subtotal", sa.Numeric(10, 2), nullable=False),
        sa.Column("profit", sa.Numeric(10, 2), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_sale_items_quantity_positive"),
    )

    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("entity_type", sa.String(30), nullable=True),
        sa.Column("entity_id", sa.Integer, nullable=True),
        sa.Column("details", sa.Text, nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("activity_logs")
    op.drop_table("sale_items")
    op.drop_index("ix_sales_receipt_number", table_name="sales")
    op.drop_table("sales")
    op.drop_table("stock_movements")
    op.drop_index("ix_medicines_supplier", table_name="medicines")
    op.drop_index("ix_medicines_generic_name", table_name="medicines")
    op.drop_table("medicines")
    op.drop_table("login_history")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
