"""add expenses table

Revision ID: 4f0d1dd96a7f
Revises: 40d4399fe5b5
Create Date: 2026-09-14 12:41:33.959062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0d1dd96a7f'
down_revision = '40d4399fe5b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('sales_receipt_number_key', 'sales', type_='unique')
    op.drop_index('ix_sales_receipt_number', table_name='sales')
    op.create_index(op.f('ix_sales_receipt_number'), 'sales', ['receipt_number'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_sales_receipt_number'), table_name='sales')
    op.create_index('ix_sales_receipt_number', 'sales', ['receipt_number'], unique=False)
    op.create_unique_constraint('sales_receipt_number_key', 'sales', ['receipt_number'])
    op.drop_table('expenses')
    # ### end Alembic commands ###
